units:
  - kilogram (kg)
  - gram (g)
  - unit (un)
  - liter (l)
  - mililiter (ml)
  - cup (cup)
  - quantity (qty)
  - tablespoon (tbsp)
  - teaspoon (tsp)
  - packet (pct)
  - can (can)
  - pound (lb)
ingredients:
  - tomato
  - salt
  - olive oil
  - garlic
  - egg
  - flour
  - corn flour
  - sugar
  - milk
  - vegetal oil
  - butter
  - baking powder
  - vanilla essence
  - yeast
  - leek
  - potato
  - parsley
  - carrot
  - onion
  - celery
  - basil
  - zucchini
  - cooking cream
  - semolina
  - nutmeg
  - black pepper
  - pecorino romano
  - parmesan
  - corn starch
  - cooked ham
  - sage leaf
  - pork ribs
  - thyme
  - red pepper
  - peeled tomato
  - paprica
  - red wine
  - bay leaf
  - cauliflower
  - lemon
  - white wine
  - italian sausage
  - brussels sprouts
  - almonds
  - bread crumbs
  - green beans
  - scallions
  - sesame seeds
  - dijon mustard
  - white wine vinegar
  - eye of round beef
  - pancetta
  - pepper
  - tomato paste
  - dried mushroom
  - ground meat
  - brocoli
conversion rules:
  - 1 un = 0.4 kg (tomato)
  - 1 un = 200 g (potato)
  - 1 cup = 0.3 l
  - 1 cup = 16 tbsp
  - 1 kg = 1000 g
  - 1 l = 1000 ml
  - 1 cup = 0.2 kg (flour)
  - 1 un = 2 tbsp (parsley)
  - 1 tbsp = 5 g (parmesan)
  - 1 un = 50 g (carrot)
recipes:
  tomato sauce:
    ingredient list:
      - 4 un tomato
      - 0.03 kg salt
      - 0.03 l olive oil
    is ingredient:
      makes 300 ml
  pasta dough:
    ingredient list:
      - 2 cup flour
      - 3 un egg
      - 0.04 kg salt
    is ingredient:
      makes 1 qty
  fettucine al pomodoro:
    ingredient list:
      - 1 qty pasta dough
      - 600 ml tomato sauce
  torta de mais:
    ingredient list:
      - 300 g corn flour
      - 400 g sugar
      - 500 ml milk
      - 100 ml vegetal oil
      - 1 tbsp butter
      - 4 un egg
      - 1 tbsp baking powder
      - 1 tsp vanilla essence
  pizza dough:
    ingredient list:
      - 2 cup flour
      - 0.04 kg salt
      - 1 pct yeast
    is ingredient:
      makes 1 qty
  vegetable stock:
    ingredient list:
      - 1 un carrot
      - 1 un onion
      - 1 un celery
      - 1 un parsley
      - 2 un basil
      - 1 un potato
      - 1 un zucchini
      - 1 un garlic
    is ingredient:
      makes 1.2 l
  parmentier:
    ingredient list:
      - 1 un leek
      - 1 tbsp olive oil
      - 1 tbsp butter
      - 300 g potato
      - 1 tbsp parsley
      - 0.78 l vegetable stock
      - 1 tbsp cooking cream
  sauce for gnocchi alla romana:
    ingredient list:
      - 0.5 l vegetable stock
      - 1 tbsp corn starch
      - 300 ml cooking cream
      - 60 g parmesan
    is ingredient:
      makes 1 qty
  gnocchi alla romana:
    ingredient list:
      - 1 l milk
      - 70 g butter
      - 210 g semolina
      - 28 g pecorino romano
      - 60 g parmesan
      - 1 un egg
      - 1 qty sauce for gnocchi alla romana
  ham and sage frittata:
    ingredient list:
      - 6 un egg
      - 0.5 cup cooked ham
      - 6 un sage leaf
      - 1 tbsp parmesan
      - 2 tbsp cooking cream
      - 2 tbsp butter      
  ribs ragu:
    ingredient list:
      - 1 un onion
      - 1 un garlic
      - 1 kg pork ribs
      - 4 tbsp olive oil
      - 1 tbsp paprica
      - 1 tbsp red pepper
      - 1 can peeled tomato
      - 1 cup red wine
      - 1 un bay leaf
      - 1 tbsp thyme
  spiced cauliflower:
    ingredient list:
      - 1 un cauliflower
      - 2 un carrot
      - 1 un garlic
      - 1 un lemon
      - 1 tbsp white wine
      - 3 tbsp olive oil
      - 0.03 kg paprica
      - 0.03 kg salt
  sausages with carrots:
    ingredient list:
      - 3 tbsp butter
      - 8 un carrot
      - 500 g italian sausage
      - 0.03 kg salt
      - 0.03 kg black pepper
  brussels sprouts with almonds:
    ingredient list:
      - 1.5 lb brussels sprouts
      - 0.25 cup butter
      - 0.25 cup almonds
      - 1 un garlic
      - 1 un lemon
      - 1.5 tsp bread crumbs
      - 0.03 kg salt
      - 0.03 kg pepper
  frosted green beans with sesame:
    ingredient list:
      - 4.25 cup green beans
      - 2 tbsp butter
      - 2 un scallions
      - 0.5 un lemon
      - 1 tbsp sesame seeds
      - 0.05 ml olive oil
      - 0.03 kg salt
      - 0.03 kg pepper
  carrots in french sauce:
    ingredient list:
      - 2 tbsp olive oil
      - 600 g carrot
      - 1 un egg
      - 1 tbsp dijon mustard
      - 1 tbsp white wine vinegar
      - 0.03 kg salt
  braised brocoli:
    ingredient list:
      - 2 tbsp olive oil
      - 2 un garlic
      - 900 g brocoli
      - 0.03 kg salt
      - 0.03 kg pepper
  florentine beef stew:
    ingredient list:
      - 3 un carrot
      - 900 g eye of round beef
      - 400 g pancetta
      - 1 un celery
      - 0.5 un onion
      - 4 tbsp olive oil
      - 0.75 cup red wine
      - 4 un tomato
      - 0.03 kg salt
      - 0.03 kg pepper
  tagliatelle with mushroom:
    ingredient list:
      - 1 qty pasta dough
      - 0.5 cup dried mushroom
      - 1 un onion
      - 2 tbsp olive oil
      - 5 tbsp white wine
      - 3 tbsp tomato paste
      - 0.5 cup parmesan
      - 0.03 kg salt
  meat frittata:
    ingredient list:
      - 0.25 cup butter
      - 300 g ground meat
      - 4 un egg
      - 1 un parsley
      - 2 tbsp milk
      - 1 tbsp olive oil
      - 0.03 kg salt
      - 0.03 kg pepper