units:
  - kilogram (kg)
  - gram (g)
  - unit (un)
  - liter (l)
  - mililiter (ml)
  - cup (cup)
  - quantity (qty)
  - tablespoon (tbsp)
  - teaspoon (tsp)
  - packet (pct)
  - can (can)
  - pound (lb)
ingredients:
  - tomato
  - salt
  - olive oil
  - garlic
  - egg
  - flour
  - corn flour
  - sugar
  - milk (l)
  - vegetal oil
  - butter
  - baking powder
  - vanilla essence
  - yeast
  - leek
  - potato
  - parsley (kg)
  - carrot
  - onion
  - celery
  - basil
  - zucchini
  - cooking cream
  - semolina
  - nutmeg
  - black pepper
  - pecorino romano
  - parmesan
  - corn starch
  - cooked ham
  - sage leaf
  - pork ribs
  - thyme
  - red pepper
  - peeled tomato
  - paprica
  - red wine
  - bay leaf
  - cauliflower
  - lemon
  - white wine
  - italian sausage
  - brussels sprouts
  - almonds
  - bread crumbs
  - green beans
  - scallions
  - sesame seeds
  - dijon mustard
  - white wine vinegar
  - eye of round beef
  - pancetta
  - pepper
  - tomato paste
  - dried mushroom
  - ground meat
  - brocoli
  - porcini
  - tarragon
  - lime juice
  - coconut aminos
  - fish sauce
  - tapioca flour
  - flank steak
  - fresh ginger
  - caper
  - coconut oil
  - raw cashew
  - clarified butter
  - cherry tomato
  - curry powder
  - spinach
  - chicken stock
  - origan
  - summer squash
  - sirloin steak
  - white mushroom
  - trout fillet
  - dry mustard
  - coriander
  - chicken broth
  - shallot
  - bacon
  - boneless beef (kg)
  - chive
  - chicken breast
  - smoked paprika
  - cayenne pepper
  - coriander
  - turnip
  - aspargus
  - ground cumin
  - mint leaf
  - lime
  - habanero chile
  - whole chicken
  - sweet potato (kg)
  - orange juice
  - chipotle chile powder
  - pork chop
  - honey
  - jalapeno
  - ancho
  - cabbage
  - cider vinegar
  - almond flour
  - tapioca flour
  - coconut flour
  - ground clove
  - cumin
  - cinnamon
  - boneless steak
  - red wine vinegar
conversion rules:
  - 1 un = 0.4 kg (tomato)
  - 1 un = 200 g (potato)
  - 1 cup = 0.3 l
  - 1 cup = 16 tbsp
  - 1 kg = 1000 g
  - 1 l = 1000 ml
  - 1 cup = 0.2 kg (flour)
  - 1 un = 2 tbsp (parsley)
  - 1 tbsp = 5 g (parmesan)
  - 1 un = 50 g (carrot)
  - 1 lb = 450 g
  - 1 tbsp = 3 tsp
recipes:
  tomato sauce:
    ingredient list:
      - 4 un tomato
      - 0.03 kg salt
      - 0.03 l olive oil
    is ingredient:
      makes 300 ml
  pasta dough:
    ingredient list:
      - 2 cup flour
      - 3 un egg
      - 0.04 kg salt
    is ingredient:
      makes 1 qty
  fettucine al pomodoro:
    ingredient list:
      - 1 qty pasta dough
      - 600 ml tomato sauce
  torta de mais:
    ingredient list:
      - 300 g corn flour
      - 400 g sugar
      - 500 ml milk
      - 100 ml vegetal oil
      - 1 tbsp butter
      - 4 un egg
      - 1 tbsp baking powder
      - 1 tsp vanilla essence
  pizza dough:
    ingredient list:
      - 2 cup flour
      - 0.04 kg salt
      - 1 pct yeast
    is ingredient:
      makes 1 qty
  vegetable stock:
    ingredient list:
      - 1 un carrot
      - 1 un onion
      - 1 un celery
      - 1 un parsley
      - 2 un basil
      - 1 un potato
      - 1 un zucchini
      - 1 un garlic
    is ingredient:
      makes 1.2 l
  parmentier:
    ingredient list:
      - 1 un leek
      - 1 tbsp olive oil
      - 1 tbsp butter
      - 300 g potato
      - 1 tbsp parsley
      - 0.78 l vegetable stock
      - 1 tbsp cooking cream
  sauce for gnocchi alla romana:
    ingredient list:
      - 0.5 l vegetable stock
      - 1 tbsp corn starch
      - 300 ml cooking cream
      - 60 g parmesan
    is ingredient:
      makes 1 qty
  gnocchi alla romana:
    ingredient list:
      - 1 l milk
      - 70 g butter
      - 210 g semolina
      - 28 g pecorino romano
      - 60 g parmesan
      - 1 un egg
      - 1 qty sauce for gnocchi alla romana
  ham and sage frittata:
    ingredient list:
      - 6 un egg
      - 0.5 cup cooked ham
      - 6 un sage leaf
      - 1 tbsp parmesan
      - 2 tbsp cooking cream
      - 2 tbsp butter      
  ribs ragu:
    ingredient list:
      - 1 un onion
      - 1 un garlic
      - 1 kg pork ribs
      - 4 tbsp olive oil
      - 1 tbsp paprica
      - 1 tbsp red pepper
      - 1 can peeled tomato
      - 1 cup red wine
      - 1 un bay leaf
      - 1 tbsp thyme
  spiced cauliflower:
    ingredient list:
      - 1 un cauliflower
      - 2 un carrot
      - 1 un garlic
      - 1 un lemon
      - 1 tbsp white wine
      - 3 tbsp olive oil
      - 0.03 kg paprica
      - 0.03 kg salt
  sausages with carrots:
    ingredient list:
      - 3 tbsp butter
      - 8 un carrot
      - 500 g italian sausage
      - 0.03 kg salt
      - 0.03 kg black pepper
  brussels sprouts with almonds:
    ingredient list:
      - 1.5 lb brussels sprouts
      - 0.25 cup butter
      - 0.25 cup almonds
      - 1 un garlic
      - 1 un lemon
      - 1.5 tsp bread crumbs
      - 0.03 kg salt
      - 0.03 kg pepper
  frosted green beans with sesame:
    ingredient list:
      - 4.25 cup green beans
      - 2 tbsp butter
      - 2 un scallions
      - 0.5 un lemon
      - 1 tbsp sesame seeds
      - 0.05 ml olive oil
      - 0.03 kg salt
      - 0.03 kg pepper
  carrots in french sauce:
    ingredient list:
      - 2 tbsp olive oil
      - 600 g carrot
      - 1 un egg
      - 1 tbsp dijon mustard
      - 1 tbsp white wine vinegar
      - 0.03 kg salt
  braised brocoli:
    ingredient list:
      - 2 tbsp olive oil
      - 2 un garlic
      - 900 g brocoli
      - 0.03 kg salt
      - 0.03 kg pepper
  florentine beef stew:
    ingredient list:
      - 3 un carrot
      - 900 g eye of round beef
      - 400 g pancetta
      - 1 un celery
      - 0.5 un onion
      - 4 tbsp olive oil
      - 0.75 cup red wine
      - 4 un tomato
      - 0.03 kg salt
      - 0.03 kg pepper
  tagliatelle with mushroom:
    ingredient list:
      - 1 qty pasta dough
      - 0.5 cup dried mushroom
      - 1 un onion
      - 2 tbsp olive oil
      - 5 tbsp white wine
      - 3 tbsp tomato paste
      - 0.5 cup parmesan
      - 0.03 kg salt
  meat frittata:
    ingredient list:
      - 0.25 cup butter
      - 300 g ground meat
      - 4 un egg
      - 1 un parsley
      - 2 tbsp milk
      - 1 tbsp olive oil
      - 0.03 kg salt
      - 0.03 kg pepper
  porcini with tarragon:
    ingredient list:
      - 8 un porcini
      - 0.25 cup butter
      - 1 tsp tarragon
      - 1 un lemon
      - 0.03 kg salt
      - 0.03 kg black pepper
  spicy korean-style stir-fried beef:
    ingredient list:
      - 0.5 cup coconut aminos
      - 4 tbsp lime juice
      - 2 tbsp fish sauce
      - 1.5 tsp tapioca flour
      - 1 lb flank steak
      - 5 un scallions
      - 4 un garlic
      - 1 tbsp fresh ginger
      - 1.5 tsp red pepper
      - 3 tbsp coconut oil
      - 3 un carrot
  umbricelli con salsa di pomodoro e capperi:
    ingredient list:
      - 600 ml tomato sauce
      - 1 qty pasta dough
      - 2 un garlic
      - 2 tbsp caper
      - 4 tbsp olive oil
      - 0.04 kg parmesan
  spiced breakfast casserole with tomatoes and spinach:
    ingredient list:
      - 0.5 cup raw cashew
      - 3 tbsp clarified butter
      - 1 un onion
      - 0.03 kg salt
      - 400 g cherry tomato
      - 2 tsp curry powder
      - 400 g spinach
      - 0.5 cup chicken broth
      - 8 un egg
  summer squash spaghetti with roasted cherry tomato sauce:
    ingredient list:
      - 800 g cherry tomato
      - 1 un shallot
      - 3 tbsp olive oil
      - 5 un garlic
      - 1 tbsp origan
      - 1 tbsp tomato paste
      - 0.25 tsp red pepper
      - 1.2 kg summer squash
      - 0.25 cup basil
  steak tips with mushroom-onion gravy:
    ingredient list:
      - 700 g sirloin steak
      - 1 tbsp olive oil
      - 400 g white mushroom
      - 1 un onion
      - 100 g porcini
      - 1 tbsp tomato paste
      - 2 un garlic
      - 0.5 tsp thyme
      - 1 tbsp parsley
  seared trout with brussels sprouts and bacon:
    ingredient list:
      - 1.5 lb brussels sprouts
      - 4 un bacon
      - 1 un shallot
      - 2 un garlic
      - 0.5 tsp thyme
      - 1 tsp coriander
      - 0.5 tsp dry mustard
      - 4 un trout fillet
      - 0.25 cup clarified butter
  latin-style chicken and cauliflower rice:
    ingredient list:
      - 2 un cauliflower
      - 500 g chicken breast
      - 3 tbsp olive oil
      - 2 un onion
      - 2 tbsp tomato paste
      - 2 tbsp origan
      - 4 un garlic
      - 4 tsp smoked paprika
      - 0.25 tsp cayenne pepper
      - 2 cup chicken broth
      - 6 tbsp coriander  
  french pot roast with mustard parlsey sauce:
    ingredient list:
      - 4 lb boneless beef
      - 1 un parsley
      - 0.25 cup chive
      - 0.25 cup dijon mustard
      - 3 tbsp white wine vinegar
      - 0.03 kg salt
      - 0.03 kg pepper
      - 1 un onion
      - 1 un celery
      - 3 un bay leaf
      - 1 lb turnip
      - 6 un carrot
      - 1 lb aspargus
  peruvian roast chicken with sweet potatoes:
    ingredient list:
      - 0.25 cup mint leaf
      - 6 un garlic 
      - 1 tbsp olive oil
      - 1 tbsp ground cumin
      - 1 tbsp honey
      - 2 tsp smoked paprika
      - 2 tsp origan
      - 2 un lime
      - 1 tsp habanero chile
      - 1 un whole chicken
      - 2 lb sweet potato
  orange chipotle-glazed pork chops:
    ingredient list:
      - 0.66 cup orange juice
      - 1.5 tsp sugar
      - 1 un lime
      - 1 tsp chipotle chile powder
      - 500 g pork chop
      - 1 tbsp olive oil
  mashed sweet potatoes:
    ingredient list:
      - 3 lb sweet potato
      - 3 tbsp clarified butter
  paleo wrap:
    ingredient list:
      - 2 cup almond flour
      - 0.75 cup tapioca flour
      - 0.25 cup coconut flour
      - 2 tsp salt
      - 2 un egg
      - 3 tbsp olive oil
    is ingredient:
      makes 12 un
  shredded beef tacos with cabbage slaw:
    ingredient list:
      - 1.25 cup cider vinegar
      - 4 tsp origan
      - 4 cup cabbage
      - 2 un carrot
      - 1 un jalapeno
      - 4 un ancho
      - 3 tbsp tomato paste
      - 6 un garlic
      - 1 tbsp cumin
      - 0.75 tsp cinnamon
      - 0.5 tsp ground clove
      - 3 un bay leaf
      - 1 un onion
      - 2 lb boneless steak
      - 1 cup coriander
      - 12 un paleo wrap
  rustic braised chicken with mushrooms:
    ingredient list:
      - 4 un bacon
      - 2 un chicken breast
      - 1 un white mushroom      
      - 1 un onion
      - 0.25 cup tomato paste
      - 3 un garlic
      - 2 tsp thyme
      - 0.25 cup parsley
      - 1 tbsp red wine vinegar